github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Tyrus]
description: [Java API for WebSocket reference implementation for easy development of WebSocket applications (JSR 356)]

latestVersion:   '1.21'
latest20Version: '2.0.7'
latest21Version: '2.1.5'

links:
  source: https://github.com/eclipse-ee4j/tyrus
  docs: https://eclipse-ee4j.github.io/tyrus-project.github.io/documentation/latest/index/
  javadocs: https://eclipse-ee4j.github.io/tyrus-project.github.io/apidocs/latest/
  download: https://github.com/eclipse-ee4j/tyrus/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/tyrus-dev
  #faq: FAQ
